name: Build and Run ChatGPT-Discord-Bot Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12.3'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest tests/
      
      # Run security check
      - name: pyupio/safety-action
        uses: pyupio/safety-action@v1.0.1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
     
  
  # Build and push package to GitHub Container Registry (GHCR)
  build-and-push:
    runs-on: ubuntu-latest 
    environment: Private Server Deploy
    needs: test  # This job depends on the CI job
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          IMAGE_NAME=ghcr.io/coder-vippro/chatgpt-discord-bot
          IMAGE_TAG=latest
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push the Docker image
        run: |
          IMAGE_NAME=ghcr.io/coder-vippro/chatgpt-discord-bot
          IMAGE_TAG=latest
          docker push $IMAGE_NAME:$IMAGE_TAG

  # Deploy from GHCR to the main server
   deploy:
    runs-on: self-hosted
    environment: Private Server Deploy
    needs: build-and-push
    steps:
      - name: Generate Kubernetes Secret YAML
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RUNWARE_API_KEY: ${{ secrets.RUNWARE_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX: ${{ secrets.GOOGLE_CX }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          cat <<EOF > bot-secrets.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: bot-secrets
          type: Opaque
          stringData:
            DISCORD_TOKEN: "$DISCORD_TOKEN"
            OPENAI_API_KEY: "$OPENAI_API_KEY"
            RUNWARE_API_KEY: "$RUNWARE_API_KEY"
            GOOGLE_API_KEY: "$GOOGLE_API_KEY"
            GOOGLE_CX: "$GOOGLE_CX"
            OPENAI_BASE_URL: "$OPENAI_BASE_URL"
            MONGODB_URI: "$MONGODB_URI"
          EOF
      
      - name: Apply Kubernetes Secret
        run: |
          kubectl apply -f bot-secrets.yaml
      
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f /home/vps/actions-runner/chatgpt-discord-bot/k3s/chatgpt-discord-bot-deployment.yaml